package com.example.pinjambuku.model

import com.example.pinjambuku.R

object ExampleBookData {
    val books = listOf(
        ExampleBook(1,"Laskar Pelangi", "Andrea Hirata", "Bentang Pustaka", "2005", "9789793062792", "Fiksi", "Amir", R.drawable.laskarpelangi,"Begitu banyak hal menakjubkan yang terjadi dalam masa kecil para anggota Laskar Pelangi. Sebelas orang anak Melayu Belitong yang luar biasa ini tak menyerah walau keadaan tak bersimpati pada mereka. Buku ini dipersembahkan buat mereka yang meyakini the magic of childhood memories, dan khususnya juga buat siapa saja yang masih meyakini adanya pintu keajaiban lain untuk mengubah dunia: pendidikan." ),
        ExampleBook(2,"5 cm", "Donny Dhirgantoro", "Grasindo", "2005", "9789797591519", "Fiksi", "Budi", R.drawable.limacm, "Lima sahabat telah menjalin persahabatan selama tujuh tahun. Mereka adalah Arial yang paling tampan, Riani sebagai satu-satunya wanita dalam kelompok itu, Zafran yang berlagak seperti seorang penyair, Ian yang paling subur badannya, dan Genta yang dianggap sebagai leader dalam kelompok itu. Suatu saat, karena terdorong oleh rasa bosan di antara satu dan yang lain, mereka memutuskan untuk tidak saling berkomunikasi dan bertemu satu sama lain selama tiga bulan. Selama tiga bulan berpisah itulah telah terjadi banyak hal yang membuat hati mereka lebih kaya dari sebelumnya."),
        ExampleBook(3,"Negeri 5 Menara", "Ahmad Fuadi", "Gramedia Pustaka Utama", "2009", "9789792248616", "Fiksi", "Cici", R.drawable.negerilimamenara, "Alif lahir di pinggir Danau Maninjau dan tidak pernah menginjak tanah di luar ranah Minangkabau. Masa kecilnya adalah berburu durian runtuh di rimba Bukit Barisan, bermain bola di sawah berlumpur dan tentu mandi berkecipak di air biru Danau Maninjau.Tiba-tiba saja dia harus naik bus tiga hari tiga malam melintasi punggung Sumatera dan Jawa menuju sebuah desa di pelosok Jawa Timur. Ibunya ingin dia menjadi Buya Hamka walau Alif ingin menjadi Habibie. Dengan setengah hati dia mengikuti perintah Ibunya: belajar di pondok."),
        ExampleBook(4,"Ayat-Ayat Cinta", "Habiburrahman El-Shirazy", "Republika-Basmala", "2007", "9789832672364", "Fiksi", "Dona", R.drawable.ayatayatcinta,"entang seorang pemuda Indonesia yang mencari ilmu jauh di tanah Arab. Berbekal iman yang kuat dan ketabahan, Fahri mengalami banyak hal yang menggetarkan hidupnya, yang sesaat membuat Fahri mempertanyakan jalan hidupnya."),
        ExampleBook(5,"Bidadari Bidadari Surga", "Tere Liye", "Republika", "2008", "9789791102261", "Fiksi", "Edi", R.drawable.bidadarisurga, "Bidadari-Bidadari Surga bercerita tentang pengorbanan seorang kakak (Laisa) untuk adik-adiknya (Dalimunte, Ikanuri, Wibisana dan Yashinta) di Lembah Lahambay agar adik-adiknya dapat melanjutkan pendidikan mereka, meski ia harus bekerja di terik matahari setiap hari, mengolah gula aren setiap jam 4 pagi serta dimalam hari menganyam rotan, meski pada dasarnya keempat adik-adiknya tersebut berasal dari darah yang berbeda dengan dirinya."),
        ExampleBook(6,"Rectoverso", "Dee Lestari", "Goodfaith", "2008", "9789799625748", "Fiksi", "Fitri", R.drawable.rectoverso, " \"Rectoverso\" merupakan hibrida dari fiksi dan musik, terdiri dari sebelas cerita pendek dan sebelas lagu yang bisa dinikmati secara terpisah maupun bersama-sama. Keduanya saling melengkapi bagaikan dua imaji yang seolah berdiri sendiri tapi sesungguhnya merupakan satu kesatuan. Inilah cermin dari dua dunia Dewi Lestari yang ia ekspresikan dalam napas kreatifitas tunggal bertajuk \"Rectoverso\". Dengar fiksinya. Baca musiknya. Lengkapi penghayatan anda dan temukanlah sebuah pengalaman baru."),
        ExampleBook(7,"Pada Sebuah Kapal", "Nh. Dini", "PT. Gramedia Pustaka Utama", "1985", "9796555867", "Fiksi", "Gozan",R.drawable.padasebuahkapal, "Setelah tunangannya (Saputro) tewas dalam kecelakaan pesawat terbang, akhirnya Sri menikah dengan Charles Vincent. Pasangan ini kemudian bermukim di Kobe, Jepang. Meskipun sudah memperoleh seorang anak dari diplomat Perancis itu, Sri sesungguhnya tidak merasa bahagia."),
    )
}